name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DioxusLabs/deploy-action
        with:
          toolSource: "mrxiaozhuox/dioxus-cli"
      # - uses: actions/checkout@v2
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: stable
      #     override: true
      #     target: wasm32-unknown-unknown
      # - uses: Swatinem/rust-cache@v1
      # - run: cargo install --git https://github.com/mrxiaozhuox/dioxus-cli

      # - name: Build
      #   run: cd . && dioxus build --release && cp ./dist/index.html ./dist/404.html

      # - name: Deploy ðŸš€
      #   uses: JamesIves/github-pages-deploy-action@v4.2.3
      #   with:
      #     branch: gh-pages
      #     folder: dist
      #     clean: false
